### ISSUE TITLE
vspec2ttl.py: string.decode not needed for Python 3

### ISSUE THREAD

**Issue by felix-loesch** [COVESA/vss-tools#108]
Hello Daniel,

vspec2ttl.py currently uses the str.decode() function to serialize the TTL file to UTF-8.
This is not needed in Python 3 and produces a warning. 
Since the other VSS Tools require Python 3 I think the decode() function can be simply removed.

**Comment by danielwilms** [comment]
Thanks for the pointer @felix-loesch. There was a PR already. I linked it with this issue.
