### ISSUE TITLE
Readme.md Getting Started instructions for pipenv appear to be incomplete

### ISSUE THREAD

**Issue by slawr** [COVESA/vss-tools#125]
I had various issues following the pipenv instructions in the Getting Started section of Readme.md in a newly migrated Ubuntu 20.04 LTS host. The pipenv installer failed to setup the PATH environment correctly and I later had problems with the dev env install. It was likely some peculiarity of my host environment but it appears the documentation may be incomplete.

In contrast using a python virtual environment, into which the pip requirements were installed was straight forward and worked.

**Comment by danielwilms** [comment]
related to #114, #75
