### ISSUE TITLE
Remove deprecated parsing code from vss-tools

### ISSUE THREAD

**Issue by SebastianSchildt** [COVESA/vss-tools#129]
We should remove remove deprecated code from vspec python package, such as anytree-less parsing and support for "list-style" before 3.0

**Comment by danielwilms** [comment]
two steps going ahead:
1. Check all tools, if they're using anytree and adapt if needed
2. Plan which features shall be supported by the main tooling.

**Comment by danielwilms** [comment]
@danielwilms

**Comment by erikbosch** [comment]
@danielwilms @SebastianSchildt - based on recent changes in tooling, can this ticket be considered "done" and be closed?

**Comment by SebastianSchildt** [comment]
Yes, can be closed. There might be more to remove, but the obviously unneeded code is already out
