### ISSUE TITLE
Create Documentation for units

### ISSUE THREAD

**Issue by oliveirarleo** [COVESA/vss-tools#132]
Currently, #104 was added, but the documentation for the tool is still missing.

**Comment by oliveirarleo** [comment]
So this brings a bigger issue: does this tool have a documentation (aside from the README.md)?

**Comment by SebastianSchildt** [comment]
It does not. And I think it should not (Maybe more .md in the Github if it is better for the structure, but no extra Hugo pages/Wikis)

**Comment by oliveirarleo** [comment]
There is the simple GitHub wiki, maybe that's the place to add this.

**Comment by danielwilms** [comment]
extra *.md file preferred, gabriel suggested TOC.

**Comment by g7fernandes** [comment]
One can use the [github-markdown-toc](https://github.com/ekalinin/github-markdown-toc) to generate table of contents with hyperlinks.

**Comment by oliveirarleo** [comment]
Yes! You may close if you wish
