### ISSUE TITLE
Millisecond data unit type is documented in VSS doc but missing in vss-tools tooling

### ISSUE THREAD

**Issue by slawr** [COVESA/vss-tools#133]
As requested in today's W3C VSS tooling call I am creating an issue to add milliseconds as a data unit type to config.yaml.

**Background**
My data model defined in vpsec requires a millisecond data unit type.

**Issue**
The VSS documentation lists [millisecond ](https://github.com/COVESA/vehicle_signal_specification/blob/965d035904a124c4b9f4a14c990dcd78e3b1b83d/docs-gen/content/rule_set/data_entry/data_unit_types.md?plain=1#L31) as an available data unit type, but it is not implemented in vss-tools [vspec/config.yaml](https://github.com/COVESA/vss-tools/blob/master/vspec/config.yaml)

**Request**
The my_config.yaml support added in #104 would be a valid workaround to the issue by allowing the vss-tools list to be extended in a private way. However this is the only data unit type I am missing and having to ship a private yaml just for it would complicate adopting the data model to the VSS eco-system. The code will also be made public as OSS. It is also a simple SI unit type. I would therefore like to add it to the standard list.

I am happy to create a PR to add it to the code, but I have been asked to raise this issue as a first step.

**Comment by oliveirarleo** [comment]
Okay, so a good idea is to guarantee that all units specified in the VSS documentation are supported. Doing it would solve your problem, but also problems like this in the future.

**Comment by erikbosch** [comment]
I have a PR open (https://github.com/COVESA/vss-tools/pull/134) to add Watt (listed in doc, currently not in config), I could add millisecond in that PR as well

**Comment by slawr** [comment]
> I have a PR open (#134) to add Watt (listed in doc, currently not in config), I could add millisecond in that PR as well

Hi Erik, PR from you, me I really don't mind if it gets it in. Looking at related commits it looks like it was a straight forward change. I have not done the coding yet so happy for you to add it to your PR. Do you want to go ahead then? We are probably approaching the point of collectively spending more time discussing then it would take to add it :)

**Comment by slawr** [comment]
@erikbosch I see you have incorporated milliseconds into #134 so I'll close this. Thanks for the change.
