### ISSUE TITLE
pip can't build wheel due to missing file

### ISSUE THREAD

**Issue by MP91** [COVESA/vss-tools#169]
error: [Errno 2] No such file or directory: 'vspec2idl.py'

run `pip install git+https://github.com/covesa/vss-tools`

**Comment by erikbosch** [comment]
I am no pip expert, this seems to be a typo. I fixed the typo in #170. That is a trivial fix so if you think that the fix seems to be corrected we could merge it.

**Comment by erikbosch** [comment]
My PR seems to have solved it when I tested locally. Please give feedback if it did not solve the error for you
