### ISSUE TITLE
Handling of orphan contrib tools (e.g. vspec2c and vspec2ocf)

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#182]
What strategy do we want to use for "orphaned" tools in contrib, like vspec2c and vspec2ocf? I.e. tools that are not functional and no-one seems to be interested in fixing them. They deteriorate over time, and now and then we get questions on them that we cannot really answer.

Some approaches I could consider:

- Create a new folder `obsolete` (or similar). If a `contrib` tool has been broken for X months, it will be moved to `obsolete` (and building it removed from `travis_optional`in `Makefile`)
- Remove the tool if it has been broken for X months

**Comment by adobekan** [comment]
Proposal:
3-6 months failing -> obsolete.
1 year in obsolete -> removed.

Document in wiki how we are handling this process and add Readme file for the obsolete dir.

**Comment by erikbosch** [comment]
@slawr - I see no problem that we change the guideline proposed in https://github.com/boschglobal/vss-tools/blob/erikbosch/erik_obsolete/README.md ("_Tools in the Obsolete Tools category may be deleted after 12 months._") to any other interval. The most important part for me is that we move them to "obsolete" to indicate that they are not functional. There is also the "may" so just that we can remove it does not mean that we absolutely need to. If something is well written but just lacks a maintainer we may keep it for longer. If something has been created quick and dirty for a specific use case that is no longer relevant we maybe want to remove it as quickly as possible.

We discussed governance for tools during the meeting. I am thinking if we possible shall do something like this:

- If no regular VSS project participant is interested in maintaining a "Community Supported Tool" then an issue `STATUS CHANGE for VSPEC2XX; Community->Contrib` shall be created, stating that the tool will change status after 6 months if no one want to step up maintaining/supporting the tool (and participating regularly in VSS meetings).
- Similar for Contrib->Obsolete. If a Contrib-tool stops working a similar issue shall be created, asking for someone to fix the problems within 6 months, otherwise it will be moved to "obsolete". 
- When a tool is moved to obsolete an issue shall be created `OBSOLETE TOOL: VSPEC2XXX`. It shall explain why the tool is considered obsolete and summarize known problems. All other issues related to the obsolete tool shall be closed (to avoid that we have more than one issue per obsolete tool). If the VSS project agrees that an obsolete tool better shall be removed a comment shall be added to the issue asking if someone has any objections to remove it. If no objections are received the tool may be removed after 12 months.
