### ISSUE TITLE
PyPI package: vspec2binary.py and vspec2ttl.py missing

### ISSUE THREAD

**Issue by d-s-e** [COVESA/vss-tools#298]
In the released PyPI package the tools `vspec2binary.py` and` vspec2ttl.py` are missing.
Is there a reason for this?

**Comment by SebastianSchildt** [comment]
`vspec2binary` needs some natively compiled part, and we have not set up a pipeline to provide builds for all the architectures supported by PyPi, therefore it includes Python-only (i.e. we only create "none"-architecture wheel)

The argument for `vspec2ttl` IIRC was that it is only contrib currently, and there have been "changes around the corner" vor vsso that would require the tool to be modified, but maybe somebody from vsso community can elaborate further. Compared to `vspec2binary`, technically speaking it would be easier to package `vspec2ttl` as I believe it is Python only

**Comment by d-s-e** [comment]
Ok, thanks.
I'm currently packaging vss-tools for our distribution and using the the PyPI package is the easiest way to do this.
So I'm wondering if it's necessary to have those two tools included, or if they are only used for some edge cases.

**Comment by erikbosch** [comment]
I think it is a fair approach that you use the pypi package, and for now assume that your users does not need the binary tool or the contrib tools (currently only vspec2ttl).
