### ISSUE TITLE
vss-tools on kuksa databroker

### ISSUE THREAD

**Issue by kulta4** [COVESA/vss-tools#320]
Hi there,
         I want to get the data in Json from eclipse kuksa databroker. From kuksa-client whatever signals given or update that should written in the format of Json. is there any change to do this??

**Comment by erikbosch** [comment]
Hi!

This is more of a Kuksa topic than a COVESA/VSS-topic, but as I am active both in VSS and Kuksa I can try to give an answer. I am also not fully sure if I understand your question correctly.

Kuksa Databroker use VSS in JSON format as input. Kuksa maintain for convenience a local copy of the corresponding released package. What is it that you are trying to achieve with kuksa-client? Read/Update signals (like `Vehicle.Speed`)? Or readining/changing/adding signals? Please provide a better description or an example. And consider raising the issue in the corresponding KUKSA repo, in [kuksa-python-sdk](https://github.com/eclipse-kuksa/kuksa-python-sdk) if the question concerns kuksa-client mostly, in [kuksa.val](https://github.com/eclipse/kuksa.val) if the question more concerns internal behavior of Databroker itself.


* [KUKSA Databroker VSS JSON](https://github.com/eclipse/kuksa.val/tree/master/data/vss-core)
* [New location in kuksa-common with same content](https://github.com/eclipse-kuksa/kuksa-common/tree/main/vss)
* [Original source of JSOn in VSS repo](https://github.com/COVESA/vehicle_signal_specification/releases/tag/v4.0)

**Comment by kulta4** [comment]
Hi,
    Thanks for your kind time. with this vss-tools we able to convert the (.vspec) to Json right. What I am asking is like vise   can we able to convert the data from kuksa-databroker/cli to Json. for now, I didn't find any way to store the vehicle signals like (vehicle.speed or Vehicle/*) as Json. even while getting metadata also values are not return there. 

target 1: connect the eclipse kuksa to eclipse hono using node red or any other protocol.

**Comment by erikbosch** [comment]
You are right, Kuksa as of today do not have any "export snapshot" function where you get all data. You could however for example with kuksa-client do `getValue -a metadata Vehicle.**` and `getValue Vehicle.**` and that way get most of the data I believe you need. I suggest that you check the Kuksa APIs (both the *.proto files and the actual Python implementation) to identify what improvements you need, if any.Then create an issue in the corresponding Kuksa repo asking for feedback. Biggest change for getting something implemented is if you are prepared to do the implementation yourself.

**Comment by erikbosch** [comment]
Closing this one as it rather concerns Kuksa than vss-tools
