### ISSUE TITLE
use apt for pipenv install

### ISSUE THREAD

**Issue by nwesem** [COVESA/vss-tools#350]
https://github.com/COVESA/vss-tools/blob/master/README.md#setup-using-venv

didn't work for me on a clean ubuntu 24.04 install, needed to install pipenv using apt so i would suggest changing this

```
export PIPENV_VENV_IN_PROJECT=1 # will create a local `.venv` in the project, otherwise uses global location
pip install pipenv
export PATH=/home/${USER}/.local/bin:${PATH}
pipenv install --dev # install the development dependencies as well
```

to

```
export PIPENV_VENV_IN_PROJECT=1 # will create a local `.venv` in the project, otherwise uses global location
sudo apt update && sudo apt install pipenv
export PATH=/home/${USER}/.local/bin:${PATH}
pipenv install --dev # install the development dependencies as well
```

**Comment by erikbosch** [comment]
We have some info at https://github.com/COVESA/vss-tools/blob/master/README.md#installing-additional-tools
It mentions protobuf-compiler there, but not golang-go. Feel free to move that information to some other place if you like.
