### ISSUE TITLE
backwards compatibility test doesn't clean up generated files

### ISSUE THREAD

**Issue by nwesem** [COVESA/vss-tools#353]
Just a minor change but we could clean up the generated files in the compatibility tests after they ran using a fixture like this:

```
@pytest.fixture(scope="function", autouse=True)
def delete_files(change_test_dir):
    yield None
    os.system("rm -f out.json out.txt")
```

**Comment by erikbosch** [comment]
Great proposal. Feel free to create a PR or add a commit to an existing one.
