### ISSUE TITLE
inconsistant requirements documentation

### ISSUE THREAD

**Issue by slawr** [COVESA/vss-tools#74]
Hi,

I noticed some inconsistencies in the documentation on requirements. README.md: section 1 lists python 3.7, section 2.1 3.8.5. I started to write a PR to fix it but realised I am not in a position to say which it should be so raised this issue instead.

[update: crossing out as now addressed] ~~I also notice that the VSS Tools section of the online VSS documentation has a Requirements sub-section that does not seem to match the README.md but perhaps there is a different intention in that section.~~ 

Regards

Steve

**Comment by slawr** [comment]
Reviewed the original issue with the feeling that the points may now be addressed due to the code changes. However I notice that the inconsistency with python versions remain. 

The second point about the online VSS doc appears to have been addressed by the removal of the requirements sub-section. Crossing through that comment.

**Comment by SebastianSchildt** [comment]
Might be adressed by #131

**Comment by danielwilms** [comment]
@erikbosch would you close this one please. Is indeed fixed as @SebastianSchildt suggested by #131

**Comment by slawr** [comment]
@danielwilms It's fine you asked erik and that he closes it - I agree with Sebastian the remaining issue is addressed by #131 - but just from the perspective of understanding how the project is set up is there a reason for preferring he does it? Like you mark it up somehow as opposed to me just closing it.

**Comment by erikbosch** [comment]
@slawr @danielwilms - I do not think it matters who close it. The issuer can always close it. Me and Magnus Feuer have been added as "outside collaborators admins" for vss-tools and can also close issues, then I assume all "COVESA github admins" (Gunnar and some more?) can close it as well.
