### ISSUE TITLE
Align documented and implemented Units

### ISSUE THREAD

**Issue by barbieri** [COVESA/vss-tools#90]
The specification documents the following units: https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_unit_types/

However the code diverges from that: https://github.com/GENIVI/vss-tools/blob/master/vspec/model/constants.py#L46

The code contains many non-[International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units) such as inch, pound, gallon...

They should be aligned and the code contain exactly what's in the documentation. If some units are missing in the docs, they should be documented.

**Comment by barbieri** [comment]
@gunnarx , @danielwilms ☝️ -- from https://github.com/GENIVI/vss-tools/pull/79#issuecomment-879278702

**Comment by erikbosch** [comment]
This is fixed now. The documentation does no longer list units, it instead refers to https://github.com/COVESA/vehicle_signal_specification/blob/master/spec/units.yaml
