### ISSUE TITLE
Handling of units in vspec2ttl

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#93]
While discussing unit support in vss I took vspec2ttl as an example, and then I noticed some things that at least seemed odd to me. Maybe @gunnarx or @danielwilms could clarify if it is a bug or a feature :-)

Two things I noticed:

- There is a mismatch between types in https://github.com/GENIVI/vss-tools/blob/master/contrib/vspec2ttl/vssotypes.py and https://github.com/GENIVI/vss-tools/blob/master/vspec/model/constants.py. For example in constants.py we have "stars", in vssotypes.py we have "N.m" 
- Why do we support alternative ways to write types in vspec2ttl, i.e. both `Nm` and `N.m`
- Does it make sense to have some types duplicated, i.e. double entries for `N.m`?

https://github.com/GENIVI/vss-tools/blob/master/contrib/vspec2ttl/vssotypes.py
```
DataUnits = {    
    'N.m': URIRef(Namespaces["cdt"]+'ucum'),
...
    'Nm': URIRef(Namespaces["qudt"]+'BendingMomentOrTorqueUnit'),
    'N.m': URIRef(Namespaces["qudt"]+'BendingMomentOrTorqueUnit'),
```

**Comment by danielwilms** [comment]
@erikbosch, it was just for now to support older vspec files. Will be removed, once we prepare it to get out of contrib. for now it's just experimental to see how we handle units.

**Comment by erikbosch** [comment]
Seems to have been fixed, closing it
